-- Drop and recreate Users table (Example)

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS restaurants CASCADE;
DROP TABLE IF EXISTS misc CASCADE;
DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  email VARCHAR(50),
  bio TEXT,
  avatar VARCHAR(255)
 );

 CREATE TABLE books (
   id SERIAL PRIMARY KEY NOT NULL,
   user_id INTEGER REFERENCES users(id) DELETE CASCADE,
   name VARCHAR(255) NOT NULL
 );

 CREATE TABLE restaurants(
   id SERIAL PRIMARY KEY NOT NULL,
   user_id INTEGER REFERENCES users(id) DELETE CASCADE,
   name VARCHAR(255) NOT NULL
 );

  CREATE TABLE movies (
   id SERIAL PRIMARY KEY NOT NULL,
   user_id INTEGER REFERENCES users(id) DELETE CASCADE,
   name VARCHAR(255) NOT NULL
 );

  CREATE TABLE products (
   id SERIAL PRIMARY KEY NOT NULL,
   user_id INTEGER REFERENCES users(id) DELETE CASCADE,
   name VARCHAR(255) NOT NULL
 );

  CREATE TABLE misc (
   id SERIAL PRIMARY KEY NOT NULL,
   user_id INTEGER REFERENCES users(id) DELETE CASCADE,
   name VARCHAR(255) NOT NULL
 );


